services:
  # БД MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_MULTIPLE_DATABASES: mydb, antennas_db
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
      - ./mysql-multiple-databases.sh:/docker-entrypoint-initdb.d/00-mysql-multiple-databases.sh
    ports:
      - "3306:3306"
    networks:
      - app-network

  # Админка для MySQL
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - mysql

  # Бэкенд на Node.js
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Первая БД
      - DB1_HOST=mysql
      - DB1_USER=user
      - DB1_PASSWORD=password
      - DB1_NAME=mydb
      # Вторая БД
      - DB2_HOST=mysql
      - DB2_USER=user
      - DB2_PASSWORD=password
      - DB2_NAME=antennas_db
    depends_on:
      - mysql
    networks:
      - app-network

  # Фронтенд на React+Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge